# src/main/resources/plugin.yml
name: ${pluginNameActual} # build.gradle에서 설정한 이름 사용
version: ${version}       # build.gradle에서 설정한 버전 사용
main: com.yourname.statplugin   # build.gradle에서 설정한 메인 클래스 경로 사용
api-version: '1.21'       # 대상 Minecraft API 버전 (Paper 1.21 기준)
author: YourName          # ★★★ 본인 이름 또는 팀 이름으로 변경 ★★★
description: A plugin to manage player stats through a GUI.
commands:
  stattree:
    description: Opens the stat tree GUI.
    usage: /stattree
    # permission: statplugin.use # 필요하다면 권한 추가
# permissions: # 필요하다면 주석 해제
#   statplugin.use:
#     description: Allows using the /stattree command.
#     default: true